# 20120456 - Lê Phước Đôn

## 6.1
### a,
Theo đề bài ta có:
q = 918293817; f = 19928 ; g = 18643
f ≈ 0.66.sqrt(q);  g ≈ 0.615.sqrt(q). Do đó ta tính được:
f^(-1) ≡ 40136186  (mod q)  và h ≡ f^(-1).g ≡ 767748560  (mod q).
\rightarrow Khoá công khai của Alice là: (q,h) = (918293817, 767748560).

### b,
Ta có:  e = 619168806 ;  0 < m < sqrt(q/4)   và   0 < r < sqrt(q/2)
<\rightarrow 0 < m < 15151   và   0 < r < 21427
Ta đi tính:
a ≡ f.e ≡ 600240756 (mod q)
Ta thấy a = 600240756  < 918293817 = q.
Tính: f(-1) ≡ 9764  (mod g)
=\rightarrow plaintext: m = f^(-1).a ≡ 9764 · 600240756 ≡ 11818 (mod g)

### c,
plaintext: m = 10220;  r = 19564
\rightarrow ciphertext: e ≡ rh + m ≡ 619167208 (mod q)
\rightarrow Bob gửi cho Alice  ciphertext e = 619167208

## 6.3
M = (5186, 2779, 5955, 2307, 6599, 6771, 6296, 7306, 4115, 7039)
The encrypted message S = 26560; multiplier A = 4392; modulus B = 8387

### Superincreasing private sequence r:
Dãy siêu tăng r của Alice là: r = (5, 14, 30, 75, 160, 351, 750, 1579, 3253, 6500)

### Decrypt the message:
Ta có: A(-1) ≡ 2683  (mod B)
\rightarrow S' ≡ A^(−1).S ≡ 4528  (mod B)
Mà 4528 = 14 + 160 + 351 + 750 + 3253
\rightarrow The plaintext x:  

## 6.6
### a, v1 = (1, 3, 2), v2 = (4, 1, −2), v3 = (−2, 1, 3)

In [32]:
import numpy as np

def gram_schmidt(A):
    """Orthogonalize a set of vectors stored as the columns of matrix A."""
    # Get the number of vectors.
    n = A.shape[1]
    for j in range(n):
        # To orthogonalize the vector in column j with respect to the
        # previous vectors, subtract from it its projection onto
        # each of the previous vectors.
        for k in range(j):
            A[:, j] -= np.dot(A[:, k], A[:, j]) * A[:, k]
        A[:, j] = A[:, j] / np.linalg.norm(A[:, j])
    return A

if __name__ == '__main__':
    A = np.array([[1.0, 3.0, 2.0], [4.0, 1.0, -2.0], [-2.0, 1.0, 3.0]])
    print(gram_schmidt(A))

[[ 0.21821789  0.88182973 -0.41803981]
 [ 0.87287156  0.01520396  0.48771311]
 [-0.43643578  0.47132279  0.76640632]]


### b, v1 = (4, 1, 3, −1), v2 = (2, 1, −3, 4), v3 = (1, 0, −2, 7)

In [33]:
import numpy as np


def gram_schmidt(A):
    """Orthogonalize a set of vectors stored as the columns of matrix A."""
    # Get the number of vectors.
    n = A.shape[1]
    for j in range(n):
        # To orthogonalize the vector in column j with respect to the
        # previous vectors, subtract from it its projection onto
        # each of the previous vectors.
        for k in range(j):
            A[:, j] -= np.dot(A[:, k], A[:, j]) * A[:, k]
        A[:, j] = A[:, j] / np.linalg.norm(A[:, j])
    return A

if __name__ == '__main__':
    A = np.array([[4.0, 1.0, 3.0, -1.0], [2.0, 1.0, -3.0, 4.0], [1.0, 0.0, -2.0, 7.0]])
    print(gram_schmidt(A))

[[ 0.87287156 -0.26726124  0.40824829 -0.57735027]
 [ 0.43643578  0.80178373 -0.40824829 -0.57735027]
 [ 0.21821789 -0.53452248 -0.81649658 -0.57735027]]


## 6.10
### b, det(A) ≠ 0. Chứng minh $A^{-1} = \dfrac{1}{det(A)}B$
Ta có $det(A) = A.B$ (theo tính chất của phần tử kề của ma trận vuông)

$\Rightarrow   A^{-1}det(A) = A^{-1}AB \\
\Leftrightarrow  A^{-1}det(A) = I_nB \\
\Leftrightarrow  A^{-1} = \dfrac{B}{det(A)}$ (đpcm)

### a, Chứng minh $AB = BA = det(A)I_n$
Ta mượn kết quả đã chứng minh ở câu b:

$
A^{-1} = B/det(A)
\Leftrightarrow  A.A^{-1} = (A.B)/det(A)
\Leftrightarrow I = (A.B)/det(A)$ (1)

và 

$A^{-1} . A = \dfrac{BA}{det(A)}
\Leftrightarrow  I = \dfrac{BA}{det(A)}$ (2)

Từ (1) và (2) suy ra: $I_n = \dfrac{AB}{det(A)} = \dfrac{BA}{det(A)}$

Hay $AB = BA = det(A)I_n$ (đpcm)




## 6.22 c = a * b modulo q

In [53]:
# A[] represents coefficients of first polynomial
# B[] represents coefficients of second polynomial
# m and n are sizes of A[] and B[] respectively
def Convolution_polynomial(a,b,N,q):
    def multiply(A, B, m, n):

        prod = [0] * (m + n - 1)

        # Multiply two polynomials term by term

        # Take ever term of first polynomial
        for i in range(m):

            # Multiply the current term of first
            # polynomial with every term of
            # second polynomial.
            for j in range(n):
                prod[i + j] += A[i] * B[j]

        return prod

    # A utility function to print a polynomial


    def printPoly(poly, n):

        for i in range(n):
            print(poly[i], end="")
            if (i != 0):
                print("x^", i, end="")
            if (i != n - 1):
                print(" + ", end="")

    # Driver Code


    # The following array represents
    # polynomial 5 + 10x^2 + 6x^3
    #A = [0, 0, 1, 0, 0,1,0,1,1,1]

    # The following array represents
    # polynomial 1 + 2x + 4x^2
    #B = [1,1,0,1,1,1,0,1,1,1]
    m = len(a)
    n = len(b)

    print("a(x) = ", end ='')
    printPoly(a, m)
    print("\nb(x) = ", end ='')
    printPoly(b, n)

    prod = multiply(a, b, m, n)

    N = 3
    q = 7
    result = [0]*N


    print("\na(x) * b(x) = ", end='')
    printPoly(prod, m+n-1)
    for i in range(m+n-1):
        if (i < N):
            result[i] = prod[i]
        if (i >= N):
            result[i % N] += prod[i]

    for i in range(N):
        if (result[i] <= (-q)/2):
            result[i] = result[i] % q
            if (result[i] > q/2):
                result[i] = result[i] - q
        elif (result[i] > q/2):
            result[i] = result[i] % q
            if (result[i] > q/2):
                result[i] = result[i] - q
            
    print("\nc(x) = a(x) * b(x)  (mod q) = ", end='')
    printPoly(result, N)

### a, N = 3, q = 7, a(x) = 1 + x, b(x) = −5 + 4x + 2x^2

In [58]:
a = [0, 1]
b = [5, 4, 2]
N = 3
q = 7
Convolution_polynomial(a,b,N,q)

a(x) = 0 + 1x^ 1
b(x) = 5 + 4x^ 1 + 2x^ 2
a(x) * b(x) = 0 + 5x^ 1 + 4x^ 2 + 2x^ 3
c(x) = a(x) * b(x)  (mod q) = 2 + -2x^ 1 + -3x^ 2

### b, N = 5, q = 4, a(x) = 2 + 2x − 2x^2 + x^3 − 2x^4;  b(x) = −1 + 3x − 3x^2 − 3x^3 − 3x^4

In [61]:
a = [0, 0, 1, 0, 0,1,0,1,1,1]
b = [1,1,0,1,1,1,0,1,1,1]
N = 5
q = 4
Convolution_polynomial(a,b,N,q)

a(x) = 0 + 0x^ 1 + 1x^ 2 + 0x^ 3 + 0x^ 4 + 1x^ 5 + 0x^ 6 + 1x^ 7 + 1x^ 8 + 1x^ 9
b(x) = 1 + 1x^ 1 + 0x^ 2 + 1x^ 3 + 1x^ 4 + 1x^ 5 + 0x^ 6 + 1x^ 7 + 1x^ 8 + 1x^ 9
a(x) * b(x) = 0 + 0x^ 1 + 1x^ 2 + 1x^ 3 + 0x^ 4 + 2x^ 5 + 2x^ 6 + 2x^ 7 + 3x^ 8 + 4x^ 9 + 4x^ 10 + 3x^ 11 + 4x^ 12 + 3x^ 13 + 3x^ 14 + 2x^ 15 + 3x^ 16 + 2x^ 17 + 1x^ 18
c(x) = a(x) * b(x)  (mod q) = 0 + -2x^ 1 + 0x^ 2

### c, N = 7, q = 3, a(x) = x + x^3;   b(x) = x + x^2 + x^4 + x^6

In [64]:
a = [0, 1, 0, 1]
b = [0, 1, 1, 0, 1, 0, 1]
N = 7
q = 3
Convolution_polynomial(a,b,N,q)

a(x) = 0 + 1x^ 1 + 0x^ 2 + 1x^ 3
b(x) = 0 + 1x^ 1 + 1x^ 2 + 0x^ 3 + 1x^ 4 + 0x^ 5 + 1x^ 6
a(x) * b(x) = 0 + 0x^ 1 + 1x^ 2 + 1x^ 3 + 1x^ 4 + 2x^ 5 + 0x^ 6 + 2x^ 7 + 0x^ 8 + 1x^ 9
c(x) = a(x) * b(x)  (mod q) = 2 + 3x^ 1 + 3x^ 2

### d, N = 10, q = 2, a(x) = x^2 + x^5 + x^7 + x^8 + x^9;    b(x) = 1+ x + x^3 + x^4 + x^5 + x^7 + x^8 + x^9

In [71]:
a = [0, 0, 1, 0, 0, 1, 0, 1, 1, 1]
b = [1, 1, 0, 1, 1, 1, 0, 1, 1, 1]
N = 10
q = 2
Convolution_polynomial(a,b,N,q)

a(x) = 0 + 0x^ 1 + 1x^ 2 + 0x^ 3 + 0x^ 4 + 1x^ 5 + 0x^ 6 + 1x^ 7 + 1x^ 8 + 1x^ 9
b(x) = 1 + 1x^ 1 + 0x^ 2 + 1x^ 3 + 1x^ 4 + 1x^ 5 + 0x^ 6 + 1x^ 7 + 1x^ 8 + 1x^ 9
a(x) * b(x) = 0 + 0x^ 1 + 1x^ 2 + 1x^ 3 + 0x^ 4 + 2x^ 5 + 2x^ 6 + 2x^ 7 + 3x^ 8 + 4x^ 9 + 4x^ 10 + 3x^ 11 + 4x^ 12 + 3x^ 13 + 3x^ 14 + 2x^ 15 + 3x^ 16 + 2x^ 17 + 1x^ 18
c(x) = a(x) * b(x)  (mod q) = 0 + -2x^ 1 + 0x^ 2